language: go
install: 
 - go get github.com/revel/revel
 - go get github.com/revel/cmd/revel

script: 
 - sh build.sh

deploy: 
 provider: releases
 api_key: 
  secure: project.hasProperty("mima") ? mima : System.getenv("mima")
 file: build/cali.tar.gz
 skip_cleanup: true
 on: 
  tags: true

